import math

"""

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""

arr= [1, 2]

x = 0

while x < 4000000:
    x = arr[-1] + arr[-2]
    arr.append(x)
    print x

y = 0

for z in arr:
    if z % 2 == 0:
        y = y + z

print y
